title: Ruh Kırkmızı Blog
remote_theme: mmistakes/jekyll-theme-basically-basic
plugins:
  - jekyll-remote-theme

# Site Settings
description: "Aracım ile ilgili zırvaladığım bir yazı derlemesi."
url: "https://burakoruk26.github.io" # Replace with your GitHub URL
baseurl: "" # Leave empty unless your site is in a subfolder
