title: Zehirli Araba Sevdası
remote_theme: mmistakes/jekyll-theme-basically-basic
plugins:
  - jekyll-remote-theme

url: "https://burakoruk26.github.io" # Replace with your GitHub URL
baseurl: "" # Leave empty unless your site is in a subfolder

exclude:
- README.md
